" use pathogen to manage plugins
filetype off 
call pathogen#helptags()
call pathogen#runtime_append_all_bundles('bundles')

" we dont care about compatibility with vi
set nocompatible

" set yanks to go to the clipboard
set clipboard=unnamed

" time to wait after ESC (default causes an annoying delay)
set timeoutlen=250

" gui options
" remove toolbar in gvim
set guioptions-=T

" enable syntax highlighting
syn on 

" whitespace options
set tabstop=4
set shiftwidth=4
set expandtab
set smarttab
set ai       " auto indent
set si       " use smart indenting
set backspace=indent,eol,start
set nowrap   " no wrapping
set wrapscan " scan for wrapping

" search options
" incremental search (search as you type)
set incsearch 

" line numbering
set nu 

" setup and show ruler
set columns=80
set ruler

" set color scheme
set backspace=start,indent,eol
set t_Co=256
colorscheme wombat256mod

" override filetype indent rules
autocmd Filetype html setlocal ts=2 sts=2 sw=2
autocmd Filetype ruby setlocal ts=2 sts=2 sw=2
autocmd Filetype javascript setlocal ts=2 sts=2 sw=2
autocmd Filetype make setlocal noexpandtab

" make twig files use jinja syntax rules
au BufRead,BufNewFile *.twig set filetype=htmljinja

" enable syntax autocompletion
filetype plugin on
set ofu=syntaxcomplete#Complete
autocmd FileType php set omnifunc=phpcomplete#CompletePHP
let php_sql_query=1                                                                                        
let php_htmlInStrings=1

" key shortcuts
" line numbering toggle
map gn :set invnu<CR>
" open up nerd tree
nmap <silent> <c-n> :NERDTreeToggle<CR>
" GRB: use fancy buffer closing that doesn't close the split
" cnoremap bd :BD<CR>
nnoremap <silent> <F8> :TlistToggle<CR>
nnoremap <silent> <F12> :bn<CR>
nnoremap <silent> <S-F12> :bp<CR>

" configure minibufexplorer
let g:miniBufExplMapWindowNavVim = 1
let g:miniBufExplMapWindowNavArrows = 1
let g:miniBufExplMapCTabSwitchBufs = 1
let g:miniBufExplModSelTarget = 1

" CTags setup
set tags=tags;$HOME " this will look in the current directory for 'tags', and work up until $HOME
let tlist_php_settings = 'php;c:class;f:function;d:constant'
let Tlist_File_Fold_Auto_Close = 1
let Tlist_WinWidth = 40
let Tlist_Close_on_Select = 1
let Tlist_Exit_OnlyWindow = 1

" CtrlP setup
