ZSH="${HOME}/.oh-my-zsh"
ZSH_THEME="refined"

plugins=(z git osx ssh-agent zsh-autosuggestions)

# SSH Agent Config
zstyle :omz:plugins:ssh-agent agent-forwarding on
zstyle :omz:plugins:ssh-agent identities id_rsa github/github_key
#eval $(keychain -q -Q --eval --agents ssh --inherit any id_rsa github/github_key)
#
source $ZSH/oh-my-zsh.sh

alias zshconfig="vim ~/.zshrc"
alias ohmyzsh="vim ~/.oh-my-zsh"
alias ls='ls -F --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias irc='screen irssi -c irc.freenode.net'

# Stop annoying 'did you mean sudo .vim'
alias sudo="nocorrect sudo"

alias v='vagrant'
alias vup="vagrant up --no-provision"
alias vdown="vagrant halt"

source ~/.bash_functions
source ~/.bash_aliases

export LESS="-r"
export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export PATH=$PATH:"/Applications/VMware Fusion.app/Contents/Library"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/gnu-sed/libexec/gnuman:$PATH"

[ -e ${HOME}/.dircolors ] && eval $(dircolors ${HOME}/.dircolors)

fpath=(/usr/local/share/zsh-completions $fpath)

# Load any private env vars
[ -s "${HOME}/.bash_private" ] && source "${HOME}/.bash_private"
[ -s "${HOME}/homebrew_env.sh" ] && source "${HOME}/homebrew_env.sh"

test -s "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

export PATH="vendor/bin:$PATH"
export PATH="node_modules/.bin:$PATH"
export PATH="/usr/local/opt/php@7.2/bin:$PATH"
export PATH="/usr/local/opt/php@7.2/sbin:$PATH"
export PATH="/usr/local/opt/mysql-client/bin:$PATH"
export PATH="/usr/local/opt/ruby/bin:$PATH"
